package com.example.gcui.model

data class GiftCardResponse(
    val activationAmount: Double,
    val activationBarcodeNumber: Any,
    val activationMaxAmt: Double,
    val activationMinAmt: Double,
    val allowedActivate: Int,
    val allowedRedeem: Int,
    val allowedReload: Int,
    val balanceBarcodeNumber: Any,
    val barcodeNumber: Any,
    val currencyCode: String,
    val denominationAmount01: Double,
    val denominationAmount02: Double,
    val description: String,
    val expiryDate: Any,
    val faceValue: Double,
    val giftCardCode: String,
    val giftCardImageUrl: String,
    val giftCardName: String,
    val giftCardPurchaseType: Any,
    val giftCardStatus: Any,
    val giftedBy: Any,
    val isFixValue: Int,
    val latestBalance: Any,
    val marketingContent01: String,
    val marketingContent02: String,
    val mobileNumber: Any,
    val productType: String,
    val purchaseContent: Any,
    val purchaseDate: Any,
    val referenceNumber: Any,
    val sharedWith: Any,
    val status: Any,
    val termAndCondition: String
)